name: Fetch LinkedIn Posts

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  fetch-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Fetch LinkedIn Posts
        run: npm run fetch:linkedin
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ORGANIZATION_URN: ${{ secrets.ORGANIZATION_URN }}

      - name: Commit & Push JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add linkedin-feed.json
          git commit -m "Updated LinkedIn feed"
          git push
